server:
  port: 8080
  servlet:
    context-path: /curd

spring:
  datasource:
    name: mydata
    url: jdbc:mysql://127.0.0.1:3306/smybatisdemo?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1qaz2wsx
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  resources:
    static-locations: classpath:/static/
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapping/*.xml  #classpath就是应用程序resources的路径
  type-aliases-package: com.chanchifeng.demo.model